"""empty message

Revision ID: 07df0ff4a031
Revises: 0fe9ef9956ab
Create Date: 2021-02-11 15:32:03.156571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07df0ff4a031'
down_revision = '0fe9ef9956ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('page_status', sa.Column('id', sa.String(length=50), nullable=False))
    op.drop_table('page_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'id')
    # ### end Alembic commands ###
