"""added sum members and favirtes to Studio

Revision ID: 1eee1aee875d
Revises: 6ae95d59d985
Create Date: 2021-07-19 23:43:41.071441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eee1aee875d'
down_revision = '6ae95d59d985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio', sa.Column('sum_favourites', sa.Integer(), nullable=True))
    op.add_column('studio', sa.Column('sum_members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio', 'sum_members')
    op.drop_column('studio', 'sum_favourites')
    # ### end Alembic commands ###
