"""empty message

Revision ID: 2de4e9e1c7de
Revises: c98e41feed23
Create Date: 2021-02-03 01:40:36.336132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de4e9e1c7de'
down_revision = 'c98e41feed23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_status',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('updating', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_status')
    # ### end Alembic commands ###
