"""empty message

Revision ID: 5ac2ec9ee1d3
Revises: f011c08d382d
Create Date: 2021-02-05 13:40:50.652035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac2ec9ee1d3'
down_revision = 'f011c08d382d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_status',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('updating', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('mal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_status')
    # ### end Alembic commands ###
