"""added average metrics to studio

Revision ID: 6ae95d59d985
Revises: 474ef74dd928
Create Date: 2021-07-19 17:58:27.244875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae95d59d985'
down_revision = '474ef74dd928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio', sa.Column('average_favourites', sa.Float(), nullable=True))
    op.add_column('studio', sa.Column('average_members', sa.Float(), nullable=True))
    op.add_column('studio', sa.Column('average_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio', 'average_score')
    op.drop_column('studio', 'average_members')
    op.drop_column('studio', 'average_favourites')
    # ### end Alembic commands ###
