"""empty message

Revision ID: 6efa7b991483
Revises: c539bfbfc104
Create Date: 2021-03-08 16:46:32.039789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efa7b991483'
down_revision = 'c539bfbfc104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('local_image_url', sa.String(length=50), nullable=True))
    op.add_column('character', sa.Column('local_image_url', sa.String(length=50), nullable=True))
    op.add_column('manga', sa.Column('local_image_url', sa.String(length=50), nullable=True))
    op.add_column('person', sa.Column('local_image_url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'local_image_url')
    op.drop_column('manga', 'local_image_url')
    op.drop_column('character', 'local_image_url')
    op.drop_column('anime', 'local_image_url')
    # ### end Alembic commands ###
