"""empty message

Revision ID: 7bc241130654
Revises: 9e3c5cce3078
Create Date: 2021-02-19 11:51:34.867094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc241130654'
down_revision = '9e3c5cce3078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'scheduled_time')
    # ### end Alembic commands ###
