"""empty message

Revision ID: 9e3c5cce3078
Revises: 07df0ff4a031
Create Date: 2021-02-11 15:33:22.491514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3c5cce3078'
down_revision = '07df0ff4a031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_status',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('updating', sa.Boolean(), nullable=True),
    sa.Column('scheduled_to_update', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_status')
    # ### end Alembic commands ###
