"""empty message

Revision ID: e4d19e444bab
Revises: aa4667a0a1a4
Create Date: 2021-02-03 01:36:03.585747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d19e444bab'
down_revision = 'aa4667a0a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_status',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('updating', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_status')
    # ### end Alembic commands ###
