"""empty message

Revision ID: e81f708e72ec
Revises: fccb2f175343
Create Date: 2021-02-03 02:16:10.066467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81f708e72ec'
down_revision = 'fccb2f175343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('creating', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'creating')
    # ### end Alembic commands ###
