"""empty message

Revision ID: f011c08d382d
Revises: e81f708e72ec
Create Date: 2021-02-05 13:32:13.115019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f011c08d382d'
down_revision = 'e81f708e72ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('page_status', sa.Column('exists', sa.Boolean(), nullable=False, server_default='0'))
    #op.drop_column('page_status', 'creating')
    op.drop_table('page_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('creating', sa.BOOLEAN(), nullable=True))
    op.drop_column('page_status', 'exists')
    # ### end Alembic commands ###
