"""empty message

Revision ID: f199c9d7d95d
Revises: 7bc241130654
Create Date: 2021-02-19 13:01:36.677684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f199c9d7d95d'
down_revision = '7bc241130654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('update_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'update_failed')
    # ### end Alembic commands ###
