"""empty message

Revision ID: fa1cb8ea4d4c
Revises: 
Create Date: 2021-02-21 23:09:11.056411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1cb8ea4d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('page_status', sa.Column('update_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'update_failed')
    op.drop_column('page_status', 'scheduled_time')
    # ### end Alembic commands ###
