"""empty message

Revision ID: fccb2f175343
Revises: 2de4e9e1c7de
Create Date: 2021-02-03 01:55:14.363420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccb2f175343'
down_revision = '2de4e9e1c7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_status', sa.Column('task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_status', 'task_id')
    # ### end Alembic commands ###
